### ISSUE TITLE
[OSX high sierra] Key- press/down/up is only called once

### ISSUE THREAD

**Issue by Mat-thieu** [WilixLead/iohook#124]
## Expected Behavior
Upon attaching key- press/down/up, the callback should be fired every time these events happen.

## Current Behavior
The callback is only fired once

## Possible Solution
No clue

## Steps to Reproduce (for bugs)
```javascript
const iohook = require('iohook');

iohook.on('keydown', event => {
  console.log(event);
});

iohook.start();
```

## Your Environment
<img width="327" alt="screen shot 2018-11-08 at 19 25 10" src="https://user-images.githubusercontent.com/7059091/48219159-127e6500-e38c-11e8-9045-50edc9239b51.png">
NodeJS: 10.11.0

**Comment by kevinresol** [comment]
I can confirm this with node (no electron)

**Comment by Djiit** [comment]
Hi there !

Thanks for your feedback. I can't reproduce this on Mojave. Will try a bit more tomorrow or later this week when I can.

**Comment by emilevirus** [comment]
I'm using only mouse events, but whenever I press a keyboard key, mouse events stop firing. I'm using MacOS High Sierra too.

**Comment by rinsuki** [comment]
me too(in mojave 10.14.1).

<details>
<summary>my log</summary>

```
$ cat index.js 
const iohook = require("iohook")

iohook.on("keydown", e => {
	console.log("down", e)
})

iohook.on("keyup", e => {
	console.log("up", e)
})

iohook.start(true)
$ node index.js 
hook_run [1121]: Accessibility API is enabled.
hook_run [1172]: CGEventTapCreate Successful.
hook_run [1178]: CFMachPortCreateRunLoopSource successful.
hook_run [1183]: CFRunLoopGetCurrent successful.
hook_run [1196]: CFRunLoopObserverCreate successful.
dispatch_event [108]: Dispatching event type 1.
hook_enable [257]: Thread Result: (0).
process_mouse_moved [882]: Mouse moved to 725, 495.
dispatch_event [108]: Dispatching event type 9.
process_mouse_moved [882]: Mouse moved to 726, 495.
dispatch_event [108]: Dispatching event type 9.
process_mouse_moved [882]: Mouse moved to 728, 496.
dispatch_event [108]: Dispatching event type 9.
process_mouse_moved [882]: Mouse moved to 729, 497.
dispatch_event [108]: Dispatching event type 9.
process_mouse_moved [882]: Mouse moved to 730, 497.
dispatch_event [108]: Dispatching event type 9.
process_mouse_moved [882]: Mouse moved to 730, 497.
dispatch_event [108]: Dispatching event type 9.
process_mouse_moved [882]: Mouse moved to 730, 497.
dispatch_event [108]: Dispatching event type 9.
process_mouse_moved [882]: Mouse moved to 731, 497.
dispatch_event [108]: Dispatching event type 9.
process_key_pressed [367]: Key 0X1E pressed. (0)
dispatch_event [108]: Dispatching event type 4.
process_key_pressed [379]: Using dispatch_sync_f for key typed events.
down { shiftKey: false,
  altKey: false,
  ctrlKey: false,
  metaKey: false,
  keycode: 30,
  rawcode: 0,
  type: 'keydown' }
^C
$ node -v
v8.12.0
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.1
BuildVersion:	18B75
```

</details>

**Comment by qbright** [comment]
is it fixed?

**Comment by Djiit** [comment]
I can't reproduce this; and I'm on Mojave.

**Comment by euroclydon37** [comment]
I just ran into this issue on a fresh project identical to the example provided and I'm using Mojave.

Just running in a raw node app, no electron involved. Node v10.10.0

**Comment by euroclydon37** [comment]
Running in debug mode and found out that it removes all callbacks. I was getting mouse events firing until a key was pressed.

**Comment by euroclydon37** [comment]
https://github.com/wilix-team/iohook/blob/8233c8af806b0c811267a6515adfa06d41edd6a7/libuiohook/src/demo_hook.c#L89

Does this line need a break? I'm only vaguely familiar with any of the C languages. But if the key is not the escape key, this switch would fall through to the key release case, right?

**Comment by Djiit** [comment]
Hi guys,

These file are part of libuiohook, the lib used by iohook. I suggest you
open an issue there.


Le jeu. 3 janv. 2019 à 18:27, Oleg Kravchenko <notifications@github.com> a
écrit :

**Comment by Xen0phobe** [comment]
I also have this problem.

**Comment by OfficialYoungX** [comment]
> Hi, i have same issue. After first keydown event callbacks stop calling.
> 
> I'm on Mojave `10.14.2`, node version `10.15.0`.
> 
> ```
> const ioHook = require('iohook');
> 
> ioHook.start(true);
> ```
> Here is debug output
> 
> ```
> hook_run [1121]: Accessibility API is enabled.
> hook_run [1172]: CGEventTapCreate Successful.
> hook_run [1178]: CFMachPortCreateRunLoopSource successful.
> hook_run [1183]: CFRunLoopGetCurrent successful.
> hook_run [1196]: CFRunLoopObserverCreate successful.
> dispatch_event [108]: Dispatching event type 1.
> hook_enable [257]: Thread Result: (0).
> process_key_pressed [367]: Key 0X39 pressed. (0X31)
> dispatch_event [108]: Dispatching event type 4.
> process_key_pressed [379]: Using dispatch_sync_f for key typed events.
>              ^C
> ```
> I commented out [this line](https://github.com/wilix-team/iohook/blob/master/libuiohook/src/darwin/input_hook.c#L380) and rebuilt the package.
> 
> I don't familiar with C, and don't know what this line does, but now all works fine.
> 
> I hoping this may be helpful

Can you tell me the detail steps to rebuild this?
I comment out this line, and try to rebuild it. But I fail to do this.
Thanks a lot !:>

**Comment by Karric** [comment]
Also having this issue, on:

ProductName:	Mac OS X, 10.14, build 18A391

**Comment by Karric** [comment]
@LastDreamer - Can you provide your steps?

**Comment by MulverineX** [comment]
@Djiit https://github.com/kwhat/libuiohook/issues/2 looks like they were having the issue, but then solved it

![image](https://user-images.githubusercontent.com/12068027/54884961-910c0880-4e3c-11e9-88a5-eefc628b683d.png)

Perhaps this was a different issue though

**Comment by MulverineX** [comment]
If it isn't, maybe this module has an outdated version of their code?

**Comment by Karric** [comment]
@MulverineX - That thread is from 2014, I doubt iohook's dependency is that old.

@Djiit - Can you weight in on this?

**Comment by Djiit** [comment]
Hi there !

I can confirm we use libuiohook v1.1 so yes, we have this fix

**Comment by Karric** [comment]
@Djiit - I'm using 'latest: 0.4.0' for iohook, and this 'fires-once' bug still persists on macOS Mojave. Do you have any recommendations? I would very much like to use this package.

**Comment by MulverineX** [comment]
https://github.com/wilix-team/iohook/issues/124#issuecomment-450697095 this comment of any help/work?

**Comment by strifel** [comment]
Just to confirm. Same problem on Mojave here

**Comment by lymne** [comment]
Same problem on Mojave here +1

**Comment by andrewkuzmych** [comment]
on Mojave +1

**Comment by anthonywebb** [comment]
I can confirm this is still an issue (high sierra)

**Comment by CupCakeArmy** [comment]
Same here 🖐
<img width="178" alt="Screenshot 2019-05-22 at 13 38 31" src="https://user-images.githubusercontent.com/14948823/58171730-eb87e080-7c96-11e9-90e8-cb1454e0c03e.png">

**Comment by leon3s** [comment]
Still have the problem there
<img width="585" alt="Capture d’écran 2019-06-05 à 13 33 21" src="https://user-images.githubusercontent.com/7750950/58953433-c3b87280-8796-11e9-8920-3631c731dbad.png">
<img width="753" alt="Capture d’écran 2019-06-05 à 13 34 07" src="https://user-images.githubusercontent.com/7750950/58953440-ca46ea00-8796-11e9-94d8-04a3423f269f.png">

**Comment by JSilversun** [comment]
I also have this problem, node 10.16.0 and mojaveOS 10.14.1

**Comment by JSilversun** [comment]
Hi! I tried the solution explained in this comment https://github.com/wilix-team/iohook/issues/124#issuecomment-451215897 and it works! Thanks @LastDreamer 

Not sure when this is going to be fixed but for now our team feels forced to make a fork of iohook until this is fixed, this bug is huge, it makes the library unusable in macOS.

See the steps to fix the library here:
1. Clone iohook repository 
`git clone https://github.com/wilix-team/iohook.git iohook`
2. Execute in terminal
`cd iohook`
3. Comment this [line](https://github.com/wilix-team/iohook/blob/master/libuiohook/src/darwin/input_hook.c#L380)

Now you need to compile the library
1. The library used to compile iohook is [cmake-js](https://github.com/cmake-js/cmake-js#readme) so for example, if you want to build the library for NodeJS v10.16.0 (My case)
You need to execute this:
`npx cmake-js compile -r node -v 10.16.0`
BTW is useful to use the --help command to see the options of `cmake-js` like this `npx cmake-js compile --help`

After the compilation is completed look for the file `build/Release/iohook.node`, this is your compiled library, now you need to move it to your project. Look in `<your_real_project>/node_modules/iohook/builds/` here you need to find the folder according to your platform and node version. For me, the folder name is `node-v64-darwin-x64`. The v64 is the ABI of the nodeJS version. If you want to find this folder more easily, in the documentation you can find a small script: https://wilix-team.github.io/iohook/manual-build.html

Just copy the script from the docs and run `node script.js`. The script will tell you the right name folder according to the node version you use to execute the script.

In few words, copy the repo, comment the line, rebuild, copy the compiled library to your real project in the real project and that's it.

Hope this helps you.

**Comment by ahkohd** [comment]
> Hi, i have same issue. After first keydown event callbacks stop calling.
> 
> I'm on Mojave `10.14.2`, node version `10.15.0`.
> 
> ```
> const ioHook = require('iohook');
> 
> ioHook.start(true);
> ```
> 
> Here is debug output
> 
> ```
> hook_run [1121]: Accessibility API is enabled.
> hook_run [1172]: CGEventTapCreate Successful.
> hook_run [1178]: CFMachPortCreateRunLoopSource successful.
> hook_run [1183]: CFRunLoopGetCurrent successful.
> hook_run [1196]: CFRunLoopObserverCreate successful.
> dispatch_event [108]: Dispatching event type 1.
> hook_enable [257]: Thread Result: (0).
> process_key_pressed [367]: Key 0X39 pressed. (0X31)
> dispatch_event [108]: Dispatching event type 4.
> process_key_pressed [379]: Using dispatch_sync_f for key typed events.
>              ^C
> ```
> 
> I commented out [this line](https://github.com/wilix-team/iohook/blob/master/libuiohook/src/darwin/input_hook.c#L380) and rebuilt the package.
> 
> I don't familiar with C, and don't know what this line does, but now all works fine.
> 
> I hoping this may be helpful

Wow, this worked!

**Comment by JoeRandom** [comment]
I tried the mentioned workaround but I am somehow not able to compile the build on MacOS 10.14.6 with Node 12.11.

Any other hint on the main issue (#124)?

`Scanning dependencies of target uiohook
[ 12%] Building C object CMakeFiles/uiohook.dir/libuiohook/src/darwin/input_helper.c.o
[ 25%] Building C object CMakeFiles/uiohook.dir/libuiohook/src/darwin/input_hook.c.o
/Users/joe/00_code/iohook/libuiohook/src/darwin/input_hook.c:601:32: error: too many arguments to function call, expected 0, have 3
                id event_data = objc_msgSend((id) objc_getClass("NSEvent"), sel_registerName("eventWithCGEvent:"), event_ref);
                                ~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/objc/message.h:62:1: note: 'objc_msgSend' declared here
OBJC_EXPORT void
^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/objc/objc-api.h:210:25: note: expanded from macro 'OBJC_EXPORT'
#   define OBJC_EXPORT  OBJC_EXTERN OBJC_VISIBLE
                        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/objc/objc-api.h:199:28: note: expanded from macro 'OBJC_EXTERN'
#       define OBJC_EXTERN extern
                           ^
/Users/joe/00_code/iohook/libuiohook/src/darwin/input_hook.c:602:36: error: too many arguments to function call, expected 0, have 2
                int subtype = (int) objc_msgSend(event_data, sel_registerName("subtype"));
                                    ~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/objc/message.h:62:1: note: 'objc_msgSend' declared here
OBJC_EXPORT void
^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/objc/objc-api.h:210:25: note: expanded from macro 'OBJC_EXPORT'
#   define OBJC_EXPORT  OBJC_EXTERN OBJC_VISIBLE
                        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/objc/objc-api.h:199:28: note: expanded from macro 'OBJC_EXTERN'
#       define OBJC_EXTERN extern
                           ^
/Users/joe/00_code/iohook/libuiohook/src/darwin/input_hook.c:612:34: error: too many arguments to function call, expected 0, have 2
                        int data = (int) objc_msgSend(event_data, sel_registerName("data1"));
                                         ~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/objc/message.h:62:1: note: 'objc_msgSend' declared here
OBJC_EXPORT void
^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/objc/objc-api.h:210:25: note: expanded from macro 'OBJC_EXPORT'
#   define OBJC_EXPORT  OBJC_EXTERN OBJC_VISIBLE
                        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/objc/objc-api.h:199:28: note: expanded from macro 'OBJC_EXTERN'
#       define OBJC_EXTERN extern
                           ^
/Users/joe/00_code/iohook/libuiohook/src/darwin/input_hook.c:1242:43: error: too many arguments to function call, expected 0, have 2
                                                                        auto_release_pool = objc_msgSend(pool, sel_registerName("init"));
                                                                                            ~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/objc/message.h:62:1: note: 'objc_msgSend' declared here
OBJC_EXPORT void
^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/objc/objc-api.h:210:25: note: expanded from macro 'OBJC_EXPORT'
#   define OBJC_EXPORT  OBJC_EXTERN OBJC_VISIBLE
                        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/objc/objc-api.h:199:28: note: expanded from macro 'OBJC_EXTERN'
#       define OBJC_EXTERN extern
                           ^
/Users/joe/00_code/iohook/libuiohook/src/darwin/input_hook.c:1251:23: error: too many arguments to function call, expected 0, have 2
                                                                        objc_msgSend(auto_release_pool, sel_registerName("release"));
                                                                        ~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/objc/message.h:62:1: note: 'objc_msgSend' declared here
OBJC_EXPORT void
^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/objc/objc-api.h:210:25: note: expanded from macro 'OBJC_EXPORT'
#   define OBJC_EXPORT  OBJC_EXTERN OBJC_VISIBLE
                        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/objc/objc-api.h:199:28: note: expanded from macro 'OBJC_EXTERN'
#       define OBJC_EXTERN extern
                           ^
5 errors generated.
make[2]: *** [CMakeFiles/uiohook.dir/libuiohook/src/darwin/input_hook.c.o] Error 1
make[1]: *** [CMakeFiles/uiohook.dir/all] Error 2
make: *** [all] Error 2
ERR! OMG Process terminated: 2`

**Comment by j0hnm4r5** [comment]
This is still an issue on Catalina 10.15

**Comment by kubamarkiewicz** [comment]
+1 on Mojave

**Comment by thebigG** [comment]
@JSilversun Thanks so much for that fix! I followed all of your steps and I managed to compile iohook from source and got the "iohook.node" compiled library.

However, when I run this
`const ioHook = require('./iohook.node');
ioHook.on('mousemove', event => {
  console.log(event); // { type: 'mousemove', x: 700, y: 400 }
});
// Register and start hook
ioHook.start();`

I get this error:

`TypeError: ioHook.on is not a function`

Any idea why this is happening?

**Comment by greggreenhaw** [comment]
Why is this not fixed yet? Is the project dead?

**Comment by thebigG** [comment]
> Why is this not fixed yet? Is the project dead?

For me the solution was just to compile directly from source directly, not through npm/nodejs or any of that. Just go to https://github.com/kwhat/libuiohook and compile it from source. This nodeJS version is just a wrapper for that one. It's much easier to just compile https://github.com/kwhat/libuiohook directly. After I compiled it from source, not weird bugs have popped in any platform!

**Comment by greggreenhaw** [comment]
Why would they just not fix the real issue

**Comment by Djiit** [comment]
Hey Greg. Thanks for your message. You are free (as in free software) to
create a PR with your solution. Any help is greatly appreciated.

--
Julien

Le sam. 25 avr. 2020 à 20:12, Greg Greenhaw <notifications@github.com> a
écrit :

**Comment by thebigG** [comment]
In my case, it wasn't just the solution but it was a much better one. But that's just me. I know some people just want to hook it into NodeJS, but for my case a bearbones C solution was actually better. But again, this was in my specific case. I don't know about anyone else's case. For more context, I used it for this https://github.com/thebigG/Tasker

**Comment by lorrylockie** [comment]
Even though the way JSilversun provides is useful, there's still hope that this problem can be solved.

**Comment by SimplexShotz** [comment]
> Hi! I tried the solution explained in this comment [#124 (comment)](https://github.com/wilix-team/iohook/issues/124#issuecomment-451215897) and it works! Thanks @LastDreamer
> 
> Not sure when this is going to be fixed but for now our team feels forced to make a fork of iohook until this is fixed, this bug is huge, it makes the library unusable in macOS.
> 
> See the steps to fix the library here:
> 
> 1. Clone iohook repository
>    `git clone https://github.com/wilix-team/iohook.git iohook`
> 2. Execute in terminal
>    `cd iohook`
> 3. Comment this [line](https://github.com/wilix-team/iohook/blob/master/libuiohook/src/darwin/input_hook.c#L380)
> 
> Now you need to compile the library
> 
> 1. The library used to compile iohook is [cmake-js](https://github.com/cmake-js/cmake-js#readme) so for example, if you want to build the library for NodeJS v10.16.0 (My case)
>    You need to execute this:
>    `npx cmake-js compile -r node -v 10.16.0`
>    BTW is useful to use the --help command to see the options of `cmake-js` like this `npx cmake-js compile --help`
> 
> After the compilation is completed look for the file `build/Release/iohook.node`, this is your compiled library, now you need to move it to your project. Look in `<your_real_project>/node_modules/iohook/builds/` here you need to find the folder according to your platform and node version. For me, the folder name is `node-v64-darwin-x64`. The v64 is the ABI of the nodeJS version. If you want to find this folder more easily, in the documentation you can find a small script: https://wilix-team.github.io/iohook/manual-build.html
> 
> Just copy the script from the docs and run `node script.js`. The script will tell you the right name folder according to the node version you use to execute the script.
> 
> In few words, copy the repo, comment the line, rebuild, copy the compiled library to your real project in the real project and that's it.
> 
> Hope this helps you.

I get to the compiling part, and I get this error:
```Scanning dependencies of target prepare_iuhook
./bootstrap.sh: line 7: autoreconf: command not found
make[2]: *** [CMakeFiles/prepare_iuhook] Error 127
make[1]: *** [CMakeFiles/prepare_iuhook.dir/all] Error 2
make: *** [all] Error 2
ERR! OMG Process terminated: 2

**Comment by samrae7** [comment]
I also have this issue on Mojave. Will try the workaround provided above. thanks.

**Comment by samrae7** [comment]
Yup https://github.com/wilix-team/iohook/issues/124#issuecomment-451215897 works for me too

**Comment by arily** [comment]
same here

and I tried to compile myself but not succeed
#include <nan.h>
         ^~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/iohook.dir/src/iohook.cc.o] Error 1
make[1]: *** [CMakeFiles/iohook.dir/all] Error 2
make: *** [all] Error 2
ERR! OMG Process terminated: 2

can anyone help me?

**Comment by m-thompson-code** [comment]
@vamshi-kura I ran into the same issue you did. I had to install some things using brew:

`brew install autoconf`
`brew install automake`
`brew install libtool`
`brew install pkg-config`

source: https://github.com/kwhat/uiohook/issues/43#issuecomment-532665952

Before this I installed cmake-js globally: `npm install -g cmake-js` (didn't notice until later that cmake-js was a dependency for iohook, so this step might not be needed.

Also I had to install cmake: b`rew install cmake`

As a note, I installed these separately in this order. I don't know if something could go wrong if you install them in a different order or at once.

Another note to add is that I had to run `npm install` inside iohook to avoid `'nan.h' file not found.` @arily 

-

node v10.22.1, npm 6.14.6, macOS Catalina version 10.15.5

**Comment by tcardlab** [comment]
Not sure why this isn't officially fixed. But, just to reiterate:

`brew install cmake automake libtool pkg-config autoconf`
Also, probably wise to ensure they are up to date. It will tell you and provide the command.
`brew upgrade package_name`

```
git clone https://github.com/wilix-team/iohook.git iohook
cd iohook
npm install   
npm install cmake-js  
npm run build
```

> Note: the jest test doesn't work as it uses a bad path. 
> Error: `Cannot find module '/Users/<username>/Documents/GitHub/iohook/builds/node-v83-darwin-x64/build/Release/iohook.node' from 'index.js'`

the last paragraph [here](https://github.com/wilix-team/iohook/issues/124#issuecomment-513026388), will tell you where to find and place the newly built package.
Node.js v14.13.0. (Seems to work, but I'll keep you posted)
npm 6.14.8
macOS Mojave version 10.14.6

**Comment by Karric** [comment]
@LastDreamer @tcardlab followed your instructions but still not seeing fixed behaviour. Can you not just fork this project with the fixed build?

**Comment by jangidsh4** [comment]
I am facing same issue on macOS Big Sur 11.1. Keydown/keyup events are called once per app. I tried the suggested fix by commenting line and using the updated iohook.node binary, but still having same issue. Any help would be appreciated.

**Comment by jangidsh4** [comment]
> I am facing same issue on macOS Big Sur 11.1. Keydown/keyup events are called once per app. I tried the suggested fix by commenting line and using the updated iohook.node binary, but still having same issue. Any help would be appreciated.

never mind, I got it working. Well documented steps by @tcardlab, followed the same but it was not working since I just copied "iohook.node" from iohook node_modules after new build by commenting suggested line. You also need to copy "uiohook.dylib" from the same folder into your ./node_modules/iohook/builds/node-v83-darwin-x64/build/release" folder. And it works. Cheers...
node v14.15.3
macOS Big Sur 11.2.1 (updated to the new patch this morning)

**Comment by ash0x0** [comment]
Is this still an issue with the current version? Someone please indicate so I can get working on this if so.

**Comment by giladdarshan** [comment]
@ash0x0, I've updated my project from using iohook 0.7.2 to 0.9.3 today, issue is still happening.
Running macOS Mojave, Node v15.11.0.

**Comment by dasilvacontin** [comment]
> @ash0x0: Is this still an issue with the current version? Someone please indicate so I can get working on this if so.

Yes, it's still happening.

macOS Ventura 13.4

node v14.21.3
