### ISSUE TITLE
Can't install on macOS Sierra 10.12.6 (node 8.9.1, npm 5.5.1)

### ISSUE THREAD

**Issue by Tom1827** [WilixLead/iohook#33]
**First**. a standard `npm install iohook` fails:

```
Toms-MacBook-Pro:node_modules tom$ npm install iohook

> segfault-handler@1.0.0 install /Users/tom/Google Drive/prog/js/airborne-cargo-drone-controller/node_modules/segfault-handler
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/segfault-handler/src/segfault-handler.o
  SOLINK_MODULE(target) Release/segfault-handler.node

> iohook@0.1.9 install /Users/tom/Google Drive/prog/js/airborne-cargo-drone-controller/node_modules/iohook
> node install.js

Downloading prebuild for platform: iohook-v0.1.9-node-v57-darwin-x64
Prebuild for current platform (iohook-v0.1.9-node-v57-darwin-x64) not found!
Try to compile for your platform:
# cd node_modules/iohook;
# npm run compile


/Users/tom/Google Drive/prog/js/airborne-cargo-drone-controller/node_modules/iohook/install.js:14
  throw err;
  ^
Prebuild for current platform (iohook-v0.1.9-node-v57-darwin-x64) not found!
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bluetooth-hci-socket@0.5.1 (node_modules/bluetooth-hci-socket):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for bluetooth-hci-socket@0.5.1: wanted {"os":"linux,android,win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: glob@7.0.6 (node_modules/usb/node_modules/node-pre-gyp/node_modules/rimraf/node_modules/glob):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Cannot read property 'type' of undefined
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: semver@5.3.0 (node_modules/usb/node_modules/node-pre-gyp/node_modules/semver):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Cannot read property 'type' of undefined
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: rimraf@2.5.4 (node_modules/usb/node_modules/node-pre-gyp/node_modules/rimraf):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Cannot read property 'type' of undefined
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: path-is-absolute@1.0.0 (node_modules/usb/node_modules/node-pre-gyp/node_modules/rimraf/node_modules/glob/node_modules/path-is-absolute):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Cannot read property 'type' of undefined
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: inflight@1.0.5 (node_modules/usb/node_modules/node-pre-gyp/node_modules/rimraf/node_modules/glob/node_modules/inflight):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Cannot read property 'type' of undefined

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iohook@0.1.9 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iohook@0.1.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tom/.npm/_logs/2017-11-18T11_53_40_338Z-debug.log
```

**Second**, while the manual build appears to work, I then get an error message when trying to use the simple example code from the iohook readme:

```
Loading native binary: /Users/tom/Google Drive/prog/js/airborne-cargo-drone-controller/node_modules/iohook/builds/node-v57-darwin-x64/build/Release/iohook.node
module.js:538
    throw err;
    ^

Error: Cannot find module '/Users/tom/Google Drive/prog/js/airborne-cargo-drone-controller/node_modules/iohook/builds/node-v57-darwin-x64/build/Release/iohook.node'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/tom/Google Drive/prog/js/airborne-cargo-drone-controller/node_modules/iohook/index.js:16:21)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

Any thoughts?

**Comment by htelsiz** [comment]
Same issue. Have you managed to resolve it?

**Comment by Tom1827** [comment]
Sorry, no.  Tried looking for other modules (it was key-up capture I needed) but ran into various problems with them too.  This ecosystem has a few issues!

**Comment by alpersilistre** [comment]
Hi, I am having the same issue. Have anybody solved this problem? Or, can you guys recommend another module with the same functionality? Thanks.

**Comment by WilixLead** [comment]
Guys, you need install XCode first. If it already installed, try open XCode and accept all licenses if it ask it. Also check XCode updates in AppStore.
At this moment I working on update for Sierra 10.13.2 and node 8+
