### ISSUE TITLE
Building for use with Electron 3.0

### ISSUE THREAD

**Issue by sgd2z** [WilixLead/iohook#98]
Since there are no prebuilt binaries for electron 3.0, I tried building iohook for use. I was succesfully able to execute npm run build (after copying the libuiohook folder from this repo into my node_modules/iohook folder). 

After this I copied the binary to the proper folder - node_modules\iohook\builds\electron-v64-win32-x64\build\Release 

## Expected Behavior
My electron app comes up normally

## Current Behavior
"Module did not self-register" error in electron. Happens at Line number in iohook/index.js:16:
`let NodeHookAddon = require(modulePath);`

## Steps to Reproduce (for bugs)
1. Build iohook
2. Copy to proper folder
3. Attempt to use in electron app

## Context
Trying to use iohook with electron 3.0 or 4.0 nightly (need events not currentaly available in 2.0)

## Your Environment
Windows 10 x64
Node 8.11
Electron 3.0 beta 5

**Comment by Djiit** [comment]
Hi there, 

Thanks for your feedback! We might need some help here, if someone has some time to test it out with a recent 3.0 beta version of electron...

**Comment by sgd2z** [comment]
I can help test if you can push up releases for 3.0.

**Comment by Djiit** [comment]
I can do that but I lack free time these days. Tell me if I can help / test
some little thing, and release newer versions!

--
Julien

Le ven. 17 août 2018 à 20:56, Siddharth Dalal <notifications@github.com> a
écrit :

**Comment by sgd2z** [comment]
I can help if you can point me in the right direction on how do I fix the "module did not self register error". If I can fix it, I'll make a PR for you

**Comment by sgd2z** [comment]
[Release.zip](https://github.com/WilixLead/iohook/files/2298419/Release.zip)

Here are my built binaries

**Comment by anoadragon453** [comment]
Also trying to build with Electron 3.0.3 but unable to. I'm available to help test!

**Comment by anoadragon453** [comment]
Oh! Does it have the ability to check when a global keyboard shortcut is released by any chance?

**Comment by thesandlord** [comment]
Looks like the latest version now has support for 3.0

The following works for me (with Node 9 and electron 3.0.6) without needing to manually compile anything.

```json
  "dependencies": {
    "iohook": "^0.2.1",
  },
  "iohook": {
    "targets": [
      "node-59",
      "electron-64"
    ],
    "platforms": [
      "win32",
      "darwin",
      "linux"
    ],
    "arches": [
      "x64",
      "ia32"
    ]
  }
```

**Comment by Djiit** [comment]
Thanks for your feedback guys ! Closing this for now.

**Comment by dobromyslov** [comment]
I was trying to build this for Electron 4. But it's not necessary. Electron 4 has already implemented it's own global shortcuts: https://electronjs.org/docs/tutorial/keyboard-shortcuts#global-shortcuts

**Comment by metacritical** [comment]
@anoadragon453 So does the release work with io-hook in electron?

**Comment by anoadragon453** [comment]
It works in electron 3.0.x, haven't tested 4.x.x yet, but I haven't seen any complaints about that version yet.

**Comment by anhang** [comment]
@anoadragon453 were you able to compile this for electron 4? I'm getting a 
`Error: The specified module could not be found.` when I run the example file, even though I copied the .node file to the right place

**Comment by anoadragon453** [comment]
@anhang not sure, but I need to for my own efforts soonish, so will report back here once I have.

**Comment by anhang** [comment]
@anoadragon453 awesome, thanks. I'm trying to debug on my side as well

**Comment by staticbass** [comment]
Any updates here? My electron app fails on startup with `Cannot find module '.../node_modules/iohook/builds/electron-v69-darwin-x64/build/Release/iohook.node'`. I tried to build it manually but it puts build into `build/node-v64-darwin-x64/build/Release` folder.

Node: 10.13.0
Electron: 4.0.8
iohook: 0.4.0

**Comment by Djiit** [comment]
Hi there ! I can use the 0.4.0 on macOS with electron 4 (warning : this issue is about electron 3).
After your update Electron, you have to : 
- adjust your settings in the `iohook` entry in your `package.json` ;
- re-install iohook so it can re-fetch the correct version (the binary exists here : https://github.com/wilix-team/iohook/releases/tag/v0.4.0).
